# coding: utf-8

# flake8: noqa

"""
MapReduce Master API

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "CancelJob200Response",
    "Error",
    "GetJobResult200Response",
    "GetJobStatus200Response",
    "HealthCheck200Response",
    "SubmitJob201Response",
    "SubmitJobRequest",
]

if True or __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from .api.default_api import DefaultApi as DefaultApi

    # import ApiClient
    from .api_response import ApiResponse as ApiResponse
    from .api_client import ApiClient as ApiClient
    from .configuration import Configuration as Configuration
    from .exceptions import OpenApiException as OpenApiException
    from .exceptions import ApiTypeError as ApiTypeError
    from .exceptions import ApiValueError as ApiValueError
    from .exceptions import ApiKeyError as ApiKeyError
    from .exceptions import ApiAttributeError as ApiAttributeError
    from .exceptions import ApiException as ApiException

    # import models into sdk package
    from .models.cancel_job200_response import (
        CancelJob200Response as CancelJob200Response,
    )
    from .models.error import Error as Error
    from .models.get_job_result200_response import (
        GetJobResult200Response as GetJobResult200Response,
    )
    from .models.get_job_status200_response import (
        GetJobStatus200Response as GetJobStatus200Response,
    )
    from .models.health_check200_response import (
        HealthCheck200Response as HealthCheck200Response,
    )
    from .models.submit_job201_response import (
        SubmitJob201Response as SubmitJob201Response,
    )
    from .models.submit_job_request import (
        SubmitJobRequest as SubmitJobRequest,
    )

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from .api.default_api import DefaultApi as DefaultApi

# import ApiClient
from .api_response import ApiResponse as ApiResponse
from .api_client import ApiClient as ApiClient
from .configuration import Configuration as Configuration
from .exceptions import OpenApiException as OpenApiException
from .exceptions import ApiTypeError as ApiTypeError
from .exceptions import ApiValueError as ApiValueError
from .exceptions import ApiKeyError as ApiKeyError
from .exceptions import ApiAttributeError as ApiAttributeError
from .exceptions import ApiException as ApiException

# import models into sdk package
from .models.cancel_job200_response import CancelJob200Response as CancelJob200Response
from .models.error import Error as Error
from .models.get_job_result200_response import GetJobResult200Response as GetJobResult200Response
from .models.get_job_status200_response import GetJobStatus200Response as GetJobStatus200Response
from .models.health_check200_response import HealthCheck200Response as HealthCheck200Response
from .models.submit_job201_response import SubmitJob201Response as SubmitJob201Response
from .models.submit_job_request import SubmitJobRequest as SubmitJobRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
