# coding: utf-8

# flake8: noqa
"""
MapReduce Master API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 0.2.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


if True or __import__("typing").TYPE_CHECKING:
    # import models into model package
    from .cancel_job200_response import CancelJob200Response
    from .error import Error
    from .get_job_result200_response import (
        GetJobResult200Response,
    )
    from .get_job_status200_response import (
        GetJobStatus200Response,
    )
    from .health_check200_response import HealthCheck200Response
    from .submit_job201_response import SubmitJob201Response
    from .submit_job_request import SubmitJobRequest

else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from .cancel_job200_response import CancelJob200Response
from .error import Error
from .get_job_result200_response import GetJobResult200Response
from .get_job_status200_response import GetJobStatus200Response
from .health_check200_response import HealthCheck200Response
from .submit_job201_response import SubmitJob201Response
from .submit_job_request import SubmitJobRequest

""",
            name=__name__,
            doc=__doc__,
        )
    )
